[project]
name = "qemu-windows-launcher"
version = "0.1.2"
description = "Helps launch Windows guests in QEMU with a single command."
readme = "README.md"
authors = [
    { name = "dasbd72", email = "twbd723@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
qemu-windows-launcher = "qemu_windows_launcher:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/qemu_windows_launcher"]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
    "types-pyyaml>=6.0.12",
    "types-requests>=2.33.0.20260906",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
